version: "3.8"

services:
    psql:
        image: postgres:16
        container_name: book-me
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: book-me
            POSTGRES_PASSWORD: secret
        networks:
            - "network"

networks:
    network:
